/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DriveRouteImport } from './routes/_drive'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as DriveDriveIndexRouteImport } from './routes/_drive/drive/index'
import { Route as DriveDriveTrashRouteImport } from './routes/_drive/drive/trash'
import { Route as DriveDriveStarredRouteImport } from './routes/_drive/drive/starred'
import { Route as DriveDriveSharedRouteImport } from './routes/_drive/drive/shared'
import { Route as DriveDriveSearchRouteImport } from './routes/_drive/drive/search'
import { Route as DriveDriveRecentRouteImport } from './routes/_drive/drive/recent'
import { Route as DriveDriveSharedIndexRouteImport } from './routes/_drive/drive/shared.index'
import { Route as DriveDriveSharedShareIdRouteImport } from './routes/_drive/drive/shared.$shareId'
import { Route as DriveDriveFoldersFolderIdRouteImport } from './routes/_drive/drive/folders.$folderId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/_drive',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const DriveDriveIndexRoute = DriveDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveTrashRoute = DriveDriveTrashRouteImport.update({
  id: '/drive/trash',
  path: '/drive/trash',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveStarredRoute = DriveDriveStarredRouteImport.update({
  id: '/drive/starred',
  path: '/drive/starred',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveSharedRoute = DriveDriveSharedRouteImport.update({
  id: '/drive/shared',
  path: '/drive/shared',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveSearchRoute = DriveDriveSearchRouteImport.update({
  id: '/drive/search',
  path: '/drive/search',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveRecentRoute = DriveDriveRecentRouteImport.update({
  id: '/drive/recent',
  path: '/drive/recent',
  getParentRoute: () => DriveRoute,
} as any)
const DriveDriveSharedIndexRoute = DriveDriveSharedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveDriveSharedRoute,
} as any)
const DriveDriveSharedShareIdRoute = DriveDriveSharedShareIdRouteImport.update({
  id: '/$shareId',
  path: '/$shareId',
  getParentRoute: () => DriveDriveSharedRoute,
} as any)
const DriveDriveFoldersFolderIdRoute =
  DriveDriveFoldersFolderIdRouteImport.update({
    id: '/drive/folders/$folderId',
    path: '/drive/folders/$folderId',
    getParentRoute: () => DriveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof PublicLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/$token': typeof ShareTokenRoute
  '/drive/recent': typeof DriveDriveRecentRoute
  '/drive/search': typeof DriveDriveSearchRoute
  '/drive/shared': typeof DriveDriveSharedRouteWithChildren
  '/drive/starred': typeof DriveDriveStarredRoute
  '/drive/trash': typeof DriveDriveTrashRoute
  '/drive/': typeof DriveDriveIndexRoute
  '/drive/folders/$folderId': typeof DriveDriveFoldersFolderIdRoute
  '/drive/shared/$shareId': typeof DriveDriveSharedShareIdRoute
  '/drive/shared/': typeof DriveDriveSharedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof PublicLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/$token': typeof ShareTokenRoute
  '/drive/recent': typeof DriveDriveRecentRoute
  '/drive/search': typeof DriveDriveSearchRoute
  '/drive/starred': typeof DriveDriveStarredRoute
  '/drive/trash': typeof DriveDriveTrashRoute
  '/drive': typeof DriveDriveIndexRoute
  '/drive/folders/$folderId': typeof DriveDriveFoldersFolderIdRoute
  '/drive/shared/$shareId': typeof DriveDriveSharedShareIdRoute
  '/drive/shared': typeof DriveDriveSharedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_drive': typeof DriveRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/$token': typeof ShareTokenRoute
  '/_public/': typeof PublicIndexRoute
  '/_drive/drive/recent': typeof DriveDriveRecentRoute
  '/_drive/drive/search': typeof DriveDriveSearchRoute
  '/_drive/drive/shared': typeof DriveDriveSharedRouteWithChildren
  '/_drive/drive/starred': typeof DriveDriveStarredRoute
  '/_drive/drive/trash': typeof DriveDriveTrashRoute
  '/_drive/drive/': typeof DriveDriveIndexRoute
  '/_drive/drive/folders/$folderId': typeof DriveDriveFoldersFolderIdRoute
  '/_drive/drive/shared/$shareId': typeof DriveDriveSharedShareIdRoute
  '/_drive/drive/shared/': typeof DriveDriveSharedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/auth/error'
    | '/share/$token'
    | '/drive/recent'
    | '/drive/search'
    | '/drive/shared'
    | '/drive/starred'
    | '/drive/trash'
    | '/drive/'
    | '/drive/folders/$folderId'
    | '/drive/shared/$shareId'
    | '/drive/shared/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/auth/error'
    | '/share/$token'
    | '/drive/recent'
    | '/drive/search'
    | '/drive/starred'
    | '/drive/trash'
    | '/drive'
    | '/drive/folders/$folderId'
    | '/drive/shared/$shareId'
    | '/drive/shared'
  id:
    | '__root__'
    | '/_drive'
    | '/_public'
    | '/_public/login'
    | '/auth/callback'
    | '/auth/error'
    | '/share/$token'
    | '/_public/'
    | '/_drive/drive/recent'
    | '/_drive/drive/search'
    | '/_drive/drive/shared'
    | '/_drive/drive/starred'
    | '/_drive/drive/trash'
    | '/_drive/drive/'
    | '/_drive/drive/folders/$folderId'
    | '/_drive/drive/shared/$shareId'
    | '/_drive/drive/shared/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DriveRoute: typeof DriveRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_drive': {
      id: '/_drive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_drive/drive/': {
      id: '/_drive/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveDriveIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/trash': {
      id: '/_drive/drive/trash'
      path: '/drive/trash'
      fullPath: '/drive/trash'
      preLoaderRoute: typeof DriveDriveTrashRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/starred': {
      id: '/_drive/drive/starred'
      path: '/drive/starred'
      fullPath: '/drive/starred'
      preLoaderRoute: typeof DriveDriveStarredRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/shared': {
      id: '/_drive/drive/shared'
      path: '/drive/shared'
      fullPath: '/drive/shared'
      preLoaderRoute: typeof DriveDriveSharedRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/search': {
      id: '/_drive/drive/search'
      path: '/drive/search'
      fullPath: '/drive/search'
      preLoaderRoute: typeof DriveDriveSearchRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/recent': {
      id: '/_drive/drive/recent'
      path: '/drive/recent'
      fullPath: '/drive/recent'
      preLoaderRoute: typeof DriveDriveRecentRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/drive/shared/': {
      id: '/_drive/drive/shared/'
      path: '/'
      fullPath: '/drive/shared/'
      preLoaderRoute: typeof DriveDriveSharedIndexRouteImport
      parentRoute: typeof DriveDriveSharedRoute
    }
    '/_drive/drive/shared/$shareId': {
      id: '/_drive/drive/shared/$shareId'
      path: '/$shareId'
      fullPath: '/drive/shared/$shareId'
      preLoaderRoute: typeof DriveDriveSharedShareIdRouteImport
      parentRoute: typeof DriveDriveSharedRoute
    }
    '/_drive/drive/folders/$folderId': {
      id: '/_drive/drive/folders/$folderId'
      path: '/drive/folders/$folderId'
      fullPath: '/drive/folders/$folderId'
      preLoaderRoute: typeof DriveDriveFoldersFolderIdRouteImport
      parentRoute: typeof DriveRoute
    }
  }
}

interface DriveDriveSharedRouteChildren {
  DriveDriveSharedShareIdRoute: typeof DriveDriveSharedShareIdRoute
  DriveDriveSharedIndexRoute: typeof DriveDriveSharedIndexRoute
}

const DriveDriveSharedRouteChildren: DriveDriveSharedRouteChildren = {
  DriveDriveSharedShareIdRoute: DriveDriveSharedShareIdRoute,
  DriveDriveSharedIndexRoute: DriveDriveSharedIndexRoute,
}

const DriveDriveSharedRouteWithChildren =
  DriveDriveSharedRoute._addFileChildren(DriveDriveSharedRouteChildren)

interface DriveRouteChildren {
  DriveDriveRecentRoute: typeof DriveDriveRecentRoute
  DriveDriveSearchRoute: typeof DriveDriveSearchRoute
  DriveDriveSharedRoute: typeof DriveDriveSharedRouteWithChildren
  DriveDriveStarredRoute: typeof DriveDriveStarredRoute
  DriveDriveTrashRoute: typeof DriveDriveTrashRoute
  DriveDriveIndexRoute: typeof DriveDriveIndexRoute
  DriveDriveFoldersFolderIdRoute: typeof DriveDriveFoldersFolderIdRoute
}

const DriveRouteChildren: DriveRouteChildren = {
  DriveDriveRecentRoute: DriveDriveRecentRoute,
  DriveDriveSearchRoute: DriveDriveSearchRoute,
  DriveDriveSharedRoute: DriveDriveSharedRouteWithChildren,
  DriveDriveStarredRoute: DriveDriveStarredRoute,
  DriveDriveTrashRoute: DriveDriveTrashRoute,
  DriveDriveIndexRoute: DriveDriveIndexRoute,
  DriveDriveFoldersFolderIdRoute: DriveDriveFoldersFolderIdRoute,
}

const DriveRouteWithChildren = DriveRoute._addFileChildren(DriveRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DriveRoute: DriveRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
